### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by abdur75648** [takimailto/BerDiff#2]
Hi @takimailto ,
It's a nice work. Looking forward to seeing the implementation of it & trying it.
If possible, please update the code.

**Comment by takimailto** [comment]
Hello @abdur75648,

Thank you so much for your support and for waiting patiently! I have updated the code, and it is now ready for use. Please feel free to try it out, and if you have any questions or feedback, do let me know. I'm looking forward to hearing about your experience and feedback!

Best regards,

**Comment by abdur75648** [comment]
Hi @takimailto Thank you very much for your response and for releasing the code.
Could you also please release the training script?
