### ISSUE TITLE
关于数据集下载的问题

### ISSUE THREAD

**Issue by uxhao-o** [takimailto/BerDiff#4]
您好，很感谢能够分享您们的研究代码！

我通过Readme里面的链接无法下载处理好的数据集，google提示我需要使用单点登录SSO，可是我似乎不能够登录。
请问能否换一下其他网盘呢？谢谢啦

**Comment by uxhao-o** [comment]
已经解决了，参考了这个issue， https://github.com/SimonKohl/probabilistic_unet/issues/14

**Comment by takimailto** [comment]
好的
