### ISSUE TITLE
Hello,can you give us the training code? I don't know how to train this model. Should I use Probabilistic Unet's training code to train our model?

### ISSUE THREAD

**Issue by sonnystalin** [takimailto/BerDiff#6]

**Comment by sonnystalin** [comment]
Hello , thank you for your excellent work ,could you please give release the training code? I don't know how to train this model, and i'm looking forward to your early reply. Thank you! @takimailto

**Comment by 1234xcs** [comment]
请问您运行 起来了吗 是用的啥运行的

**Comment by takimailto** [comment]
Thank you for reading the paper! The training code is similiar with the training code of improved diffusion (https://github.com/openai/improved-diffusion/blob/main/improved_diffusion/train_util.py), and we will release our version recently.

**Comment by 1234xcs** [comment]
很期待 你们的代码 希望近期能公布 祝你们好运

**Comment by takimailto** [comment]
Please refer to the newly added directory "training".

**Comment by sonnystalin** [comment]
Thank you for your excellent work!
